name: action_tds
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: ^4.6.5
  flutter: 
    sdk: flutter
  #   logger: ^2.0.2+1
  #   get_storage: ^2.1.1
  #   animated_theme_switcher: ^2.0.8
  #   flutter_linkify: ^6.0.0
  #   google_fonts: ^6.1.0
  #   url_launcher: ^6.1.14
  #   carousel_slider: ^4.2.1
  #   flutter_staggered_grid_view: ^0.7.0
  #   auto_size_text: ^3.0.0
  #   money_formatter: ^0.0.5
  #   gradient_icon: ^2.0.0
  #   flutter_svg: ^2.0.9
  #   persistent_bottom_nav_bar: ^5.0.2
  #   carousel_indicator: ^1.0.6
  #   simple_circular_progress_bar: ^1.0.2
  #   font_awesome_flutter: ^10.6.0
  #   random_name_generator: ^1.2.0
  #   animated_toast_list: ^1.0.2
  #   device_preview: ^1.1.0
  #   provider: ^6.0.5
  #   workmanager: ^0.5.2
  #   home_widget: ^0.3.0
  #   flutter_local_notifications: ^16.1.0
  #   timezone: ^0.9.2
  #   flutter_timezone: ^1.0.8
  #   change_app_package_name: ^1.1.0
  #   firebase_core: ^2.21.0
  #   firebase_messaging: ^14.7.3
  #   custom_refresh_indicator: ^3.0.0
  #   fluttertoast: ^8.2.4
  #   skeletonizer: ^0.8.0
  #   go_router: ^12.1.1
  #   cherry_toast: ^1.2.0
  #   slide_countdown: ^1.1.1
  #   intl: ^0.18.1
  #   fast_cached_network_image: ^1.2.0
  #   path_provider: ^2.1.1
  #   flutter_cache_manager: ^3.3.1
  #   cached_network_image: ^3.3.0
  #   hexcolor: ^3.0.1
  #   share_plus: ^7.2.1
  #   csc_picker: ^0.2.7
  #   flutter_in_app_pip: ^1.7.3
  #   video_player: ^2.8.1
  #   flutter_widget_from_html: ^0.14.6
  #   socket_io_client: ^2.0.3+1
  #   pusher_channels_flutter: ^2.2.0
  #   flutter_keyboard_visibility: ^5.4.1
  #   lottie: ^2.7.0
  #   model_viewer_plus: ^1.7.0
  #   flutter_custom_tabs: ^1.2.1
  #   timelines: ^0.1.0
  #   o3d: ^2.0.0
  #   nb_utils: ^6.0.6
  #   great_list_view: ^0.2.3
  #   device_info_plus: ^9.1.1
  #   shared_preferences: ^2.2.2
  #   version: ^2.0.3
  #   http: ^1.1.0
  #   package_info_plus: ^4.2.0
  #   flutter_rating_bar: ^4.0.1
  #   image_cropper: ^5.0.0
  #   image_picker: ^1.0.4
  #   path_drawing: ^1.0.1
  #   popover: ^0.2.8+2
  #   ensure_visible_when_focused: ^1.2.0
  #   path: ^1.8.3
  #   name: your_flutter_app
  # description: Your Flutter App Description
  # version: 1.0.0

  # Utils
  logger: ^2.0.2+1
  get_storage: ^2.1.1
  animated_theme_switcher: ^2.0.8
  flutter_linkify: ^6.0.0
  google_fonts: ^6.1.0
  url_launcher: ^6.1.14

  # UI Components
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  auto_size_text: ^3.0.0
  gradient_icon: ^2.0.0
  flutter_svg: ^2.0.9

  # Navigation and State Management
  persistent_bottom_nav_bar: ^5.0.2
  carousel_indicator: ^1.0.6
  simple_circular_progress_bar: ^1.0.2
  font_awesome_flutter: ^10.6.0
  random_name_generator: ^1.2.0
  animated_toast_list: ^1.0.2
  device_preview: ^1.1.0
  provider: ^6.0.5
  workmanager: ^0.5.2
  home_widget: ^0.3.0

  # Notifications and Time
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8

  # Firebase
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3

  # UI Widgets
  custom_refresh_indicator: ^3.0.0
  fluttertoast: ^8.2.4
  skeletonizer: ^0.8.0
  go_router: ^12.1.1
  cherry_toast: ^1.2.0
  slide_countdown: ^1.1.1

  # Internationalization
  intl: ^0.18.1

  # Image Handling
  fast_cached_network_image: ^1.2.0
  path_provider: ^2.1.1
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.0
  hexcolor: ^3.0.1
  share_plus: ^7.2.1

  # Form Elements
  csc_picker: ^0.2.7
  flutter_in_app_pip: ^1.7.3

  # Multimedia
  video_player: ^2.8.1
  flutter_widget_from_html: ^0.14.6

  # Communication
  socket_io_client: ^2.0.3+1
  pusher_channels_flutter: ^2.2.0

  # UI Animation and Presentation
  flutter_keyboard_visibility: ^5.4.1
  lottie: ^2.7.0
  model_viewer_plus: ^1.7.0
  flutter_custom_tabs: ^1.2.1
  timelines: ^0.1.0
  o3d: ^2.0.0

  # Utility Functions and Helpers
  nb_utils: ^6.0.6
  money_formatter: ^0.0.5

  # UI Widgets and Components
  great_list_view: ^0.2.3

  # Device Information
  device_info_plus: ^9.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # App Versioning and Upgrades
  version: ^2.0.3

  # HTTP and Network
  http: ^1.1.0

  # App Information
  package_info_plus: ^4.2.0

  # UI Components
  flutter_rating_bar: ^4.0.1
  image_cropper: ^5.0.0
  image_picker: ^1.0.4

  # Drawing and Animation
  path_drawing: ^1.0.1
  popover: ^0.2.8+2

  # UI Interaction
  ensure_visible_when_focused: ^1.2.0

  # File and Path Handling
  path: ^1.8.3
  xml: ^6.3.0
  permission_handler: ^11.0.1




dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  # App Versioning and Upgrades
  change_app_package_name: ^1.1.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/images/app/
    - assets/images/plane_indicator/
    - assets/videos/
    - assets/svgs/
    - assets/lottie/
    - assets/fonts/
    - assets/models/

    # values
    - android/app/src/main/res/values/strings.xml

