// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFMGdXRIR1K-Z9SIhCVmDOEFpt6gVoil8',
    appId: '1:882974995452:web:4200128fc1dd9715353879',
    messagingSenderId: '882974995452',
    projectId: 'action-demo-34fef',
    authDomain: 'action-demo-34fef.firebaseapp.com',
    storageBucket: 'action-demo-34fef.appspot.com',
    measurementId: 'G-QSZY2V4JKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSW1VrrYGwG2NLClq_rmoTi3sfWeYxEs',
    appId: '1:882974995452:android:3948de445404456c353879',
    messagingSenderId: '882974995452',
    projectId: 'action-demo-34fef',
    storageBucket: 'action-demo-34fef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJzD-yU5U2xacHudb74jrD_PR13p1kseI',
    appId: '1:882974995452:ios:12caa50db815bd97353879',
    messagingSenderId: '882974995452',
    projectId: 'action-demo-34fef',
    storageBucket: 'action-demo-34fef.appspot.com',
    iosBundleId: 'com.touchwood.auction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJzD-yU5U2xacHudb74jrD_PR13p1kseI',
    appId: '1:882974995452:ios:dbd1d0e9cfef84c7353879',
    messagingSenderId: '882974995452',
    projectId: 'action-demo-34fef',
    storageBucket: 'action-demo-34fef.appspot.com',
    iosBundleId: 'com.example.auctionTds.RunnerTests',
  );
}
